// Code generated by ent, DO NOT EDIT.

package onchaindepositscanstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the onchaindepositscanstate type in the database.
	Label = "onchain_deposit_scan_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldChain holds the string denoting the chain field in the database.
	FieldChain = "chain"
	// FieldLastScannedBlock holds the string denoting the last_scanned_block field in the database.
	FieldLastScannedBlock = "last_scanned_block"
	// Table holds the table name of the onchaindepositscanstate in the database.
	Table = "onchain_deposit_scan_states"
)

// Columns holds all SQL columns for onchaindepositscanstate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldChain,
	FieldLastScannedBlock,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	ChainValidator func(string) error
	// DefaultLastScannedBlock holds the default value on creation for the "last_scanned_block" field.
	DefaultLastScannedBlock int64
)

// OrderOption defines the ordering options for the OnchainDepositScanState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByChain orders the results by the chain field.
func ByChain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChain, opts...).ToFunc()
}

// ByLastScannedBlock orders the results by the last_scanned_block field.
func ByLastScannedBlock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastScannedBlock, opts...).ToFunc()
}
