// Code generated by ent, DO NOT EDIT.

package onchaindepositscanstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldUpdatedAt, v))
}

// Chain applies equality check predicate on the "chain" field. It's identical to ChainEQ.
func Chain(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldChain, v))
}

// LastScannedBlock applies equality check predicate on the "last_scanned_block" field. It's identical to LastScannedBlockEQ.
func LastScannedBlock(v int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldLastScannedBlock, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLTE(FieldUpdatedAt, v))
}

// ChainEQ applies the EQ predicate on the "chain" field.
func ChainEQ(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldChain, v))
}

// ChainNEQ applies the NEQ predicate on the "chain" field.
func ChainNEQ(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNEQ(FieldChain, v))
}

// ChainIn applies the In predicate on the "chain" field.
func ChainIn(vs ...string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldIn(FieldChain, vs...))
}

// ChainNotIn applies the NotIn predicate on the "chain" field.
func ChainNotIn(vs ...string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNotIn(FieldChain, vs...))
}

// ChainGT applies the GT predicate on the "chain" field.
func ChainGT(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGT(FieldChain, v))
}

// ChainGTE applies the GTE predicate on the "chain" field.
func ChainGTE(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGTE(FieldChain, v))
}

// ChainLT applies the LT predicate on the "chain" field.
func ChainLT(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLT(FieldChain, v))
}

// ChainLTE applies the LTE predicate on the "chain" field.
func ChainLTE(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLTE(FieldChain, v))
}

// ChainContains applies the Contains predicate on the "chain" field.
func ChainContains(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldContains(FieldChain, v))
}

// ChainHasPrefix applies the HasPrefix predicate on the "chain" field.
func ChainHasPrefix(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldHasPrefix(FieldChain, v))
}

// ChainHasSuffix applies the HasSuffix predicate on the "chain" field.
func ChainHasSuffix(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldHasSuffix(FieldChain, v))
}

// ChainEqualFold applies the EqualFold predicate on the "chain" field.
func ChainEqualFold(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEqualFold(FieldChain, v))
}

// ChainContainsFold applies the ContainsFold predicate on the "chain" field.
func ChainContainsFold(v string) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldContainsFold(FieldChain, v))
}

// LastScannedBlockEQ applies the EQ predicate on the "last_scanned_block" field.
func LastScannedBlockEQ(v int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldEQ(FieldLastScannedBlock, v))
}

// LastScannedBlockNEQ applies the NEQ predicate on the "last_scanned_block" field.
func LastScannedBlockNEQ(v int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNEQ(FieldLastScannedBlock, v))
}

// LastScannedBlockIn applies the In predicate on the "last_scanned_block" field.
func LastScannedBlockIn(vs ...int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldIn(FieldLastScannedBlock, vs...))
}

// LastScannedBlockNotIn applies the NotIn predicate on the "last_scanned_block" field.
func LastScannedBlockNotIn(vs ...int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldNotIn(FieldLastScannedBlock, vs...))
}

// LastScannedBlockGT applies the GT predicate on the "last_scanned_block" field.
func LastScannedBlockGT(v int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGT(FieldLastScannedBlock, v))
}

// LastScannedBlockGTE applies the GTE predicate on the "last_scanned_block" field.
func LastScannedBlockGTE(v int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldGTE(FieldLastScannedBlock, v))
}

// LastScannedBlockLT applies the LT predicate on the "last_scanned_block" field.
func LastScannedBlockLT(v int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLT(FieldLastScannedBlock, v))
}

// LastScannedBlockLTE applies the LTE predicate on the "last_scanned_block" field.
func LastScannedBlockLTE(v int64) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.FieldLTE(FieldLastScannedBlock, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OnchainDepositScanState) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OnchainDepositScanState) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OnchainDepositScanState) predicate.OnchainDepositScanState {
	return predicate.OnchainDepositScanState(sql.NotPredicates(p))
}
