// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchaindeposit"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OnchainDepositUpdate is the builder for updating OnchainDeposit entities.
type OnchainDepositUpdate struct {
	config
	hooks    []Hook
	mutation *OnchainDepositMutation
}

// Where appends a list predicates to the OnchainDepositUpdate builder.
func (_u *OnchainDepositUpdate) Where(ps ...predicate.OnchainDeposit) *OnchainDepositUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OnchainDepositUpdate) SetUpdatedAt(v time.Time) *OnchainDepositUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OnchainDepositUpdate) SetUserID(v int64) *OnchainDepositUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableUserID(v *int64) *OnchainDepositUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OnchainDepositUpdate) AddUserID(v int64) *OnchainDepositUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetChain sets the "chain" field.
func (_u *OnchainDepositUpdate) SetChain(v string) *OnchainDepositUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableChain(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetTokenSymbol sets the "token_symbol" field.
func (_u *OnchainDepositUpdate) SetTokenSymbol(v string) *OnchainDepositUpdate {
	_u.mutation.SetTokenSymbol(v)
	return _u
}

// SetNillableTokenSymbol sets the "token_symbol" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableTokenSymbol(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetTokenSymbol(*v)
	}
	return _u
}

// SetTokenContract sets the "token_contract" field.
func (_u *OnchainDepositUpdate) SetTokenContract(v string) *OnchainDepositUpdate {
	_u.mutation.SetTokenContract(v)
	return _u
}

// SetNillableTokenContract sets the "token_contract" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableTokenContract(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetTokenContract(*v)
	}
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *OnchainDepositUpdate) SetTxHash(v string) *OnchainDepositUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableTxHash(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetLogIndex sets the "log_index" field.
func (_u *OnchainDepositUpdate) SetLogIndex(v int64) *OnchainDepositUpdate {
	_u.mutation.ResetLogIndex()
	_u.mutation.SetLogIndex(v)
	return _u
}

// SetNillableLogIndex sets the "log_index" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableLogIndex(v *int64) *OnchainDepositUpdate {
	if v != nil {
		_u.SetLogIndex(*v)
	}
	return _u
}

// AddLogIndex adds value to the "log_index" field.
func (_u *OnchainDepositUpdate) AddLogIndex(v int64) *OnchainDepositUpdate {
	_u.mutation.AddLogIndex(v)
	return _u
}

// SetBlockNumber sets the "block_number" field.
func (_u *OnchainDepositUpdate) SetBlockNumber(v int64) *OnchainDepositUpdate {
	_u.mutation.ResetBlockNumber()
	_u.mutation.SetBlockNumber(v)
	return _u
}

// SetNillableBlockNumber sets the "block_number" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableBlockNumber(v *int64) *OnchainDepositUpdate {
	if v != nil {
		_u.SetBlockNumber(*v)
	}
	return _u
}

// AddBlockNumber adds value to the "block_number" field.
func (_u *OnchainDepositUpdate) AddBlockNumber(v int64) *OnchainDepositUpdate {
	_u.mutation.AddBlockNumber(v)
	return _u
}

// SetBlockHash sets the "block_hash" field.
func (_u *OnchainDepositUpdate) SetBlockHash(v string) *OnchainDepositUpdate {
	_u.mutation.SetBlockHash(v)
	return _u
}

// SetNillableBlockHash sets the "block_hash" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableBlockHash(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetBlockHash(*v)
	}
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *OnchainDepositUpdate) SetFromAddress(v string) *OnchainDepositUpdate {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableFromAddress(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetToAddress sets the "to_address" field.
func (_u *OnchainDepositUpdate) SetToAddress(v string) *OnchainDepositUpdate {
	_u.mutation.SetToAddress(v)
	return _u
}

// SetNillableToAddress sets the "to_address" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableToAddress(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetToAddress(*v)
	}
	return _u
}

// SetAmountRaw sets the "amount_raw" field.
func (_u *OnchainDepositUpdate) SetAmountRaw(v string) *OnchainDepositUpdate {
	_u.mutation.SetAmountRaw(v)
	return _u
}

// SetNillableAmountRaw sets the "amount_raw" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableAmountRaw(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetAmountRaw(*v)
	}
	return _u
}

// SetAmountCredit sets the "amount_credit" field.
func (_u *OnchainDepositUpdate) SetAmountCredit(v float64) *OnchainDepositUpdate {
	_u.mutation.ResetAmountCredit()
	_u.mutation.SetAmountCredit(v)
	return _u
}

// SetNillableAmountCredit sets the "amount_credit" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableAmountCredit(v *float64) *OnchainDepositUpdate {
	if v != nil {
		_u.SetAmountCredit(*v)
	}
	return _u
}

// AddAmountCredit adds value to the "amount_credit" field.
func (_u *OnchainDepositUpdate) AddAmountCredit(v float64) *OnchainDepositUpdate {
	_u.mutation.AddAmountCredit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OnchainDepositUpdate) SetStatus(v string) *OnchainDepositUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableStatus(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *OnchainDepositUpdate) SetCreditedAt(v time.Time) *OnchainDepositUpdate {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableCreditedAt(v *time.Time) *OnchainDepositUpdate {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *OnchainDepositUpdate) ClearCreditedAt() *OnchainDepositUpdate {
	_u.mutation.ClearCreditedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *OnchainDepositUpdate) SetErrorMessage(v string) *OnchainDepositUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableErrorMessage(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *OnchainDepositUpdate) ClearErrorMessage() *OnchainDepositUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the OnchainDepositMutation object of the builder.
func (_u *OnchainDepositUpdate) Mutation() *OnchainDepositMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OnchainDepositUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OnchainDepositUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OnchainDepositUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OnchainDepositUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OnchainDepositUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := onchaindeposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OnchainDepositUpdate) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := onchaindeposit.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenSymbol(); ok {
		if err := onchaindeposit.TokenSymbolValidator(v); err != nil {
			return &ValidationError{Name: "token_symbol", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.token_symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenContract(); ok {
		if err := onchaindeposit.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.token_contract": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TxHash(); ok {
		if err := onchaindeposit.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockHash(); ok {
		if err := onchaindeposit.BlockHashValidator(v); err != nil {
			return &ValidationError{Name: "block_hash", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.block_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := onchaindeposit.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToAddress(); ok {
		if err := onchaindeposit.ToAddressValidator(v); err != nil {
			return &ValidationError{Name: "to_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.to_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountRaw(); ok {
		if err := onchaindeposit.AmountRawValidator(v); err != nil {
			return &ValidationError{Name: "amount_raw", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.amount_raw": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := onchaindeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OnchainDepositUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onchaindeposit.Table, onchaindeposit.Columns, sqlgraph.NewFieldSpec(onchaindeposit.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(onchaindeposit.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(onchaindeposit.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(onchaindeposit.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenSymbol(); ok {
		_spec.SetField(onchaindeposit.FieldTokenSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenContract(); ok {
		_spec.SetField(onchaindeposit.FieldTokenContract, field.TypeString, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(onchaindeposit.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogIndex(); ok {
		_spec.SetField(onchaindeposit.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLogIndex(); ok {
		_spec.AddField(onchaindeposit.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlockNumber(); ok {
		_spec.SetField(onchaindeposit.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlockNumber(); ok {
		_spec.AddField(onchaindeposit.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlockHash(); ok {
		_spec.SetField(onchaindeposit.FieldBlockHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(onchaindeposit.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToAddress(); ok {
		_spec.SetField(onchaindeposit.FieldToAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountRaw(); ok {
		_spec.SetField(onchaindeposit.FieldAmountRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCredit(); ok {
		_spec.SetField(onchaindeposit.FieldAmountCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCredit(); ok {
		_spec.AddField(onchaindeposit.FieldAmountCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(onchaindeposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(onchaindeposit.FieldCreditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(onchaindeposit.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(onchaindeposit.FieldErrorMessage, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onchaindeposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OnchainDepositUpdateOne is the builder for updating a single OnchainDeposit entity.
type OnchainDepositUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OnchainDepositMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OnchainDepositUpdateOne) SetUpdatedAt(v time.Time) *OnchainDepositUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OnchainDepositUpdateOne) SetUserID(v int64) *OnchainDepositUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableUserID(v *int64) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OnchainDepositUpdateOne) AddUserID(v int64) *OnchainDepositUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetChain sets the "chain" field.
func (_u *OnchainDepositUpdateOne) SetChain(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableChain(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetTokenSymbol sets the "token_symbol" field.
func (_u *OnchainDepositUpdateOne) SetTokenSymbol(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetTokenSymbol(v)
	return _u
}

// SetNillableTokenSymbol sets the "token_symbol" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableTokenSymbol(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetTokenSymbol(*v)
	}
	return _u
}

// SetTokenContract sets the "token_contract" field.
func (_u *OnchainDepositUpdateOne) SetTokenContract(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetTokenContract(v)
	return _u
}

// SetNillableTokenContract sets the "token_contract" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableTokenContract(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetTokenContract(*v)
	}
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *OnchainDepositUpdateOne) SetTxHash(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableTxHash(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetLogIndex sets the "log_index" field.
func (_u *OnchainDepositUpdateOne) SetLogIndex(v int64) *OnchainDepositUpdateOne {
	_u.mutation.ResetLogIndex()
	_u.mutation.SetLogIndex(v)
	return _u
}

// SetNillableLogIndex sets the "log_index" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableLogIndex(v *int64) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetLogIndex(*v)
	}
	return _u
}

// AddLogIndex adds value to the "log_index" field.
func (_u *OnchainDepositUpdateOne) AddLogIndex(v int64) *OnchainDepositUpdateOne {
	_u.mutation.AddLogIndex(v)
	return _u
}

// SetBlockNumber sets the "block_number" field.
func (_u *OnchainDepositUpdateOne) SetBlockNumber(v int64) *OnchainDepositUpdateOne {
	_u.mutation.ResetBlockNumber()
	_u.mutation.SetBlockNumber(v)
	return _u
}

// SetNillableBlockNumber sets the "block_number" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableBlockNumber(v *int64) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetBlockNumber(*v)
	}
	return _u
}

// AddBlockNumber adds value to the "block_number" field.
func (_u *OnchainDepositUpdateOne) AddBlockNumber(v int64) *OnchainDepositUpdateOne {
	_u.mutation.AddBlockNumber(v)
	return _u
}

// SetBlockHash sets the "block_hash" field.
func (_u *OnchainDepositUpdateOne) SetBlockHash(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetBlockHash(v)
	return _u
}

// SetNillableBlockHash sets the "block_hash" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableBlockHash(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetBlockHash(*v)
	}
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *OnchainDepositUpdateOne) SetFromAddress(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableFromAddress(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetToAddress sets the "to_address" field.
func (_u *OnchainDepositUpdateOne) SetToAddress(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetToAddress(v)
	return _u
}

// SetNillableToAddress sets the "to_address" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableToAddress(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetToAddress(*v)
	}
	return _u
}

// SetAmountRaw sets the "amount_raw" field.
func (_u *OnchainDepositUpdateOne) SetAmountRaw(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetAmountRaw(v)
	return _u
}

// SetNillableAmountRaw sets the "amount_raw" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableAmountRaw(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetAmountRaw(*v)
	}
	return _u
}

// SetAmountCredit sets the "amount_credit" field.
func (_u *OnchainDepositUpdateOne) SetAmountCredit(v float64) *OnchainDepositUpdateOne {
	_u.mutation.ResetAmountCredit()
	_u.mutation.SetAmountCredit(v)
	return _u
}

// SetNillableAmountCredit sets the "amount_credit" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableAmountCredit(v *float64) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetAmountCredit(*v)
	}
	return _u
}

// AddAmountCredit adds value to the "amount_credit" field.
func (_u *OnchainDepositUpdateOne) AddAmountCredit(v float64) *OnchainDepositUpdateOne {
	_u.mutation.AddAmountCredit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OnchainDepositUpdateOne) SetStatus(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableStatus(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *OnchainDepositUpdateOne) SetCreditedAt(v time.Time) *OnchainDepositUpdateOne {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableCreditedAt(v *time.Time) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *OnchainDepositUpdateOne) ClearCreditedAt() *OnchainDepositUpdateOne {
	_u.mutation.ClearCreditedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *OnchainDepositUpdateOne) SetErrorMessage(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableErrorMessage(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *OnchainDepositUpdateOne) ClearErrorMessage() *OnchainDepositUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the OnchainDepositMutation object of the builder.
func (_u *OnchainDepositUpdateOne) Mutation() *OnchainDepositMutation {
	return _u.mutation
}

// Where appends a list predicates to the OnchainDepositUpdate builder.
func (_u *OnchainDepositUpdateOne) Where(ps ...predicate.OnchainDeposit) *OnchainDepositUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OnchainDepositUpdateOne) Select(field string, fields ...string) *OnchainDepositUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OnchainDeposit entity.
func (_u *OnchainDepositUpdateOne) Save(ctx context.Context) (*OnchainDeposit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OnchainDepositUpdateOne) SaveX(ctx context.Context) *OnchainDeposit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OnchainDepositUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OnchainDepositUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OnchainDepositUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := onchaindeposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OnchainDepositUpdateOne) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := onchaindeposit.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenSymbol(); ok {
		if err := onchaindeposit.TokenSymbolValidator(v); err != nil {
			return &ValidationError{Name: "token_symbol", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.token_symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenContract(); ok {
		if err := onchaindeposit.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.token_contract": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TxHash(); ok {
		if err := onchaindeposit.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockHash(); ok {
		if err := onchaindeposit.BlockHashValidator(v); err != nil {
			return &ValidationError{Name: "block_hash", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.block_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := onchaindeposit.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToAddress(); ok {
		if err := onchaindeposit.ToAddressValidator(v); err != nil {
			return &ValidationError{Name: "to_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.to_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountRaw(); ok {
		if err := onchaindeposit.AmountRawValidator(v); err != nil {
			return &ValidationError{Name: "amount_raw", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.amount_raw": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := onchaindeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OnchainDepositUpdateOne) sqlSave(ctx context.Context) (_node *OnchainDeposit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onchaindeposit.Table, onchaindeposit.Columns, sqlgraph.NewFieldSpec(onchaindeposit.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OnchainDeposit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onchaindeposit.FieldID)
		for _, f := range fields {
			if !onchaindeposit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != onchaindeposit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(onchaindeposit.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(onchaindeposit.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(onchaindeposit.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenSymbol(); ok {
		_spec.SetField(onchaindeposit.FieldTokenSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenContract(); ok {
		_spec.SetField(onchaindeposit.FieldTokenContract, field.TypeString, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(onchaindeposit.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogIndex(); ok {
		_spec.SetField(onchaindeposit.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLogIndex(); ok {
		_spec.AddField(onchaindeposit.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlockNumber(); ok {
		_spec.SetField(onchaindeposit.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlockNumber(); ok {
		_spec.AddField(onchaindeposit.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlockHash(); ok {
		_spec.SetField(onchaindeposit.FieldBlockHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(onchaindeposit.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToAddress(); ok {
		_spec.SetField(onchaindeposit.FieldToAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountRaw(); ok {
		_spec.SetField(onchaindeposit.FieldAmountRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCredit(); ok {
		_spec.SetField(onchaindeposit.FieldAmountCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCredit(); ok {
		_spec.AddField(onchaindeposit.FieldAmountCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(onchaindeposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(onchaindeposit.FieldCreditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(onchaindeposit.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(onchaindeposit.FieldErrorMessage, field.TypeString)
	}
	_node = &OnchainDeposit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onchaindeposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
