// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/onchaindepositscanstate"
)

// OnchainDepositScanState is the model entity for the OnchainDepositScanState schema.
type OnchainDepositScanState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Chain holds the value of the "chain" field.
	Chain string `json:"chain,omitempty"`
	// LastScannedBlock holds the value of the "last_scanned_block" field.
	LastScannedBlock int64 `json:"last_scanned_block,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OnchainDepositScanState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case onchaindepositscanstate.FieldID, onchaindepositscanstate.FieldLastScannedBlock:
			values[i] = new(sql.NullInt64)
		case onchaindepositscanstate.FieldChain:
			values[i] = new(sql.NullString)
		case onchaindepositscanstate.FieldCreatedAt, onchaindepositscanstate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OnchainDepositScanState fields.
func (_m *OnchainDepositScanState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case onchaindepositscanstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case onchaindepositscanstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case onchaindepositscanstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case onchaindepositscanstate.FieldChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chain", values[i])
			} else if value.Valid {
				_m.Chain = value.String
			}
		case onchaindepositscanstate.FieldLastScannedBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_scanned_block", values[i])
			} else if value.Valid {
				_m.LastScannedBlock = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OnchainDepositScanState.
// This includes values selected through modifiers, order, etc.
func (_m *OnchainDepositScanState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OnchainDepositScanState.
// Note that you need to call OnchainDepositScanState.Unwrap() before calling this method if this OnchainDepositScanState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OnchainDepositScanState) Update() *OnchainDepositScanStateUpdateOne {
	return NewOnchainDepositScanStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OnchainDepositScanState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OnchainDepositScanState) Unwrap() *OnchainDepositScanState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OnchainDepositScanState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OnchainDepositScanState) String() string {
	var builder strings.Builder
	builder.WriteString("OnchainDepositScanState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("chain=")
	builder.WriteString(_m.Chain)
	builder.WriteString(", ")
	builder.WriteString("last_scanned_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastScannedBlock))
	builder.WriteByte(')')
	return builder.String()
}

// OnchainDepositScanStates is a parsable slice of OnchainDepositScanState.
type OnchainDepositScanStates []*OnchainDepositScanState
