// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchaindepositscanstate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OnchainDepositScanStateDelete is the builder for deleting a OnchainDepositScanState entity.
type OnchainDepositScanStateDelete struct {
	config
	hooks    []Hook
	mutation *OnchainDepositScanStateMutation
}

// Where appends a list predicates to the OnchainDepositScanStateDelete builder.
func (_d *OnchainDepositScanStateDelete) Where(ps ...predicate.OnchainDepositScanState) *OnchainDepositScanStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OnchainDepositScanStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OnchainDepositScanStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OnchainDepositScanStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(onchaindepositscanstate.Table, sqlgraph.NewFieldSpec(onchaindepositscanstate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OnchainDepositScanStateDeleteOne is the builder for deleting a single OnchainDepositScanState entity.
type OnchainDepositScanStateDeleteOne struct {
	_d *OnchainDepositScanStateDelete
}

// Where appends a list predicates to the OnchainDepositScanStateDelete builder.
func (_d *OnchainDepositScanStateDeleteOne) Where(ps ...predicate.OnchainDepositScanState) *OnchainDepositScanStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OnchainDepositScanStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{onchaindepositscanstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OnchainDepositScanStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
