// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/onchaindeposit"
)

// OnchainDeposit is the model entity for the OnchainDeposit schema.
type OnchainDeposit struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Chain holds the value of the "chain" field.
	Chain string `json:"chain,omitempty"`
	// TokenSymbol holds the value of the "token_symbol" field.
	TokenSymbol string `json:"token_symbol,omitempty"`
	// TokenContract holds the value of the "token_contract" field.
	TokenContract string `json:"token_contract,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash string `json:"tx_hash,omitempty"`
	// LogIndex holds the value of the "log_index" field.
	LogIndex int64 `json:"log_index,omitempty"`
	// BlockNumber holds the value of the "block_number" field.
	BlockNumber int64 `json:"block_number,omitempty"`
	// BlockHash holds the value of the "block_hash" field.
	BlockHash string `json:"block_hash,omitempty"`
	// FromAddress holds the value of the "from_address" field.
	FromAddress string `json:"from_address,omitempty"`
	// ToAddress holds the value of the "to_address" field.
	ToAddress string `json:"to_address,omitempty"`
	// AmountRaw holds the value of the "amount_raw" field.
	AmountRaw string `json:"amount_raw,omitempty"`
	// AmountCredit holds the value of the "amount_credit" field.
	AmountCredit float64 `json:"amount_credit,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreditedAt holds the value of the "credited_at" field.
	CreditedAt *time.Time `json:"credited_at,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OnchainDeposit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case onchaindeposit.FieldAmountCredit:
			values[i] = new(sql.NullFloat64)
		case onchaindeposit.FieldID, onchaindeposit.FieldUserID, onchaindeposit.FieldLogIndex, onchaindeposit.FieldBlockNumber:
			values[i] = new(sql.NullInt64)
		case onchaindeposit.FieldChain, onchaindeposit.FieldTokenSymbol, onchaindeposit.FieldTokenContract, onchaindeposit.FieldTxHash, onchaindeposit.FieldBlockHash, onchaindeposit.FieldFromAddress, onchaindeposit.FieldToAddress, onchaindeposit.FieldAmountRaw, onchaindeposit.FieldStatus, onchaindeposit.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case onchaindeposit.FieldCreatedAt, onchaindeposit.FieldUpdatedAt, onchaindeposit.FieldCreditedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OnchainDeposit fields.
func (_m *OnchainDeposit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case onchaindeposit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case onchaindeposit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case onchaindeposit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case onchaindeposit.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case onchaindeposit.FieldChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chain", values[i])
			} else if value.Valid {
				_m.Chain = value.String
			}
		case onchaindeposit.FieldTokenSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_symbol", values[i])
			} else if value.Valid {
				_m.TokenSymbol = value.String
			}
		case onchaindeposit.FieldTokenContract:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_contract", values[i])
			} else if value.Valid {
				_m.TokenContract = value.String
			}
		case onchaindeposit.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = value.String
			}
		case onchaindeposit.FieldLogIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field log_index", values[i])
			} else if value.Valid {
				_m.LogIndex = value.Int64
			}
		case onchaindeposit.FieldBlockNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field block_number", values[i])
			} else if value.Valid {
				_m.BlockNumber = value.Int64
			}
		case onchaindeposit.FieldBlockHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field block_hash", values[i])
			} else if value.Valid {
				_m.BlockHash = value.String
			}
		case onchaindeposit.FieldFromAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_address", values[i])
			} else if value.Valid {
				_m.FromAddress = value.String
			}
		case onchaindeposit.FieldToAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_address", values[i])
			} else if value.Valid {
				_m.ToAddress = value.String
			}
		case onchaindeposit.FieldAmountRaw:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount_raw", values[i])
			} else if value.Valid {
				_m.AmountRaw = value.String
			}
		case onchaindeposit.FieldAmountCredit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_credit", values[i])
			} else if value.Valid {
				_m.AmountCredit = value.Float64
			}
		case onchaindeposit.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case onchaindeposit.FieldCreditedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field credited_at", values[i])
			} else if value.Valid {
				_m.CreditedAt = new(time.Time)
				*_m.CreditedAt = value.Time
			}
		case onchaindeposit.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OnchainDeposit.
// This includes values selected through modifiers, order, etc.
func (_m *OnchainDeposit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OnchainDeposit.
// Note that you need to call OnchainDeposit.Unwrap() before calling this method if this OnchainDeposit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OnchainDeposit) Update() *OnchainDepositUpdateOne {
	return NewOnchainDepositClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OnchainDeposit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OnchainDeposit) Unwrap() *OnchainDeposit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OnchainDeposit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OnchainDeposit) String() string {
	var builder strings.Builder
	builder.WriteString("OnchainDeposit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("chain=")
	builder.WriteString(_m.Chain)
	builder.WriteString(", ")
	builder.WriteString("token_symbol=")
	builder.WriteString(_m.TokenSymbol)
	builder.WriteString(", ")
	builder.WriteString("token_contract=")
	builder.WriteString(_m.TokenContract)
	builder.WriteString(", ")
	builder.WriteString("tx_hash=")
	builder.WriteString(_m.TxHash)
	builder.WriteString(", ")
	builder.WriteString("log_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogIndex))
	builder.WriteString(", ")
	builder.WriteString("block_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockNumber))
	builder.WriteString(", ")
	builder.WriteString("block_hash=")
	builder.WriteString(_m.BlockHash)
	builder.WriteString(", ")
	builder.WriteString("from_address=")
	builder.WriteString(_m.FromAddress)
	builder.WriteString(", ")
	builder.WriteString("to_address=")
	builder.WriteString(_m.ToAddress)
	builder.WriteString(", ")
	builder.WriteString("amount_raw=")
	builder.WriteString(_m.AmountRaw)
	builder.WriteString(", ")
	builder.WriteString("amount_credit=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCredit))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.CreditedAt; v != nil {
		builder.WriteString("credited_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// OnchainDeposits is a parsable slice of OnchainDeposit.
type OnchainDeposits []*OnchainDeposit
