// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchaindeposit"
)

// OnchainDepositCreate is the builder for creating a OnchainDeposit entity.
type OnchainDepositCreate struct {
	config
	mutation *OnchainDepositMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OnchainDepositCreate) SetCreatedAt(v time.Time) *OnchainDepositCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableCreatedAt(v *time.Time) *OnchainDepositCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OnchainDepositCreate) SetUpdatedAt(v time.Time) *OnchainDepositCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableUpdatedAt(v *time.Time) *OnchainDepositCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OnchainDepositCreate) SetUserID(v int64) *OnchainDepositCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetChain sets the "chain" field.
func (_c *OnchainDepositCreate) SetChain(v string) *OnchainDepositCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetTokenSymbol sets the "token_symbol" field.
func (_c *OnchainDepositCreate) SetTokenSymbol(v string) *OnchainDepositCreate {
	_c.mutation.SetTokenSymbol(v)
	return _c
}

// SetTokenContract sets the "token_contract" field.
func (_c *OnchainDepositCreate) SetTokenContract(v string) *OnchainDepositCreate {
	_c.mutation.SetTokenContract(v)
	return _c
}

// SetTxHash sets the "tx_hash" field.
func (_c *OnchainDepositCreate) SetTxHash(v string) *OnchainDepositCreate {
	_c.mutation.SetTxHash(v)
	return _c
}

// SetLogIndex sets the "log_index" field.
func (_c *OnchainDepositCreate) SetLogIndex(v int64) *OnchainDepositCreate {
	_c.mutation.SetLogIndex(v)
	return _c
}

// SetBlockNumber sets the "block_number" field.
func (_c *OnchainDepositCreate) SetBlockNumber(v int64) *OnchainDepositCreate {
	_c.mutation.SetBlockNumber(v)
	return _c
}

// SetBlockHash sets the "block_hash" field.
func (_c *OnchainDepositCreate) SetBlockHash(v string) *OnchainDepositCreate {
	_c.mutation.SetBlockHash(v)
	return _c
}

// SetFromAddress sets the "from_address" field.
func (_c *OnchainDepositCreate) SetFromAddress(v string) *OnchainDepositCreate {
	_c.mutation.SetFromAddress(v)
	return _c
}

// SetToAddress sets the "to_address" field.
func (_c *OnchainDepositCreate) SetToAddress(v string) *OnchainDepositCreate {
	_c.mutation.SetToAddress(v)
	return _c
}

// SetAmountRaw sets the "amount_raw" field.
func (_c *OnchainDepositCreate) SetAmountRaw(v string) *OnchainDepositCreate {
	_c.mutation.SetAmountRaw(v)
	return _c
}

// SetAmountCredit sets the "amount_credit" field.
func (_c *OnchainDepositCreate) SetAmountCredit(v float64) *OnchainDepositCreate {
	_c.mutation.SetAmountCredit(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OnchainDepositCreate) SetStatus(v string) *OnchainDepositCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableStatus(v *string) *OnchainDepositCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreditedAt sets the "credited_at" field.
func (_c *OnchainDepositCreate) SetCreditedAt(v time.Time) *OnchainDepositCreate {
	_c.mutation.SetCreditedAt(v)
	return _c
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableCreditedAt(v *time.Time) *OnchainDepositCreate {
	if v != nil {
		_c.SetCreditedAt(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *OnchainDepositCreate) SetErrorMessage(v string) *OnchainDepositCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableErrorMessage(v *string) *OnchainDepositCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// Mutation returns the OnchainDepositMutation object of the builder.
func (_c *OnchainDepositCreate) Mutation() *OnchainDepositMutation {
	return _c.mutation
}

// Save creates the OnchainDeposit in the database.
func (_c *OnchainDepositCreate) Save(ctx context.Context) (*OnchainDeposit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OnchainDepositCreate) SaveX(ctx context.Context) *OnchainDeposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OnchainDepositCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OnchainDepositCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OnchainDepositCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := onchaindeposit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := onchaindeposit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := onchaindeposit.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OnchainDepositCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OnchainDeposit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OnchainDeposit.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OnchainDeposit.user_id"`)}
	}
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "OnchainDeposit.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := onchaindeposit.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenSymbol(); !ok {
		return &ValidationError{Name: "token_symbol", err: errors.New(`ent: missing required field "OnchainDeposit.token_symbol"`)}
	}
	if v, ok := _c.mutation.TokenSymbol(); ok {
		if err := onchaindeposit.TokenSymbolValidator(v); err != nil {
			return &ValidationError{Name: "token_symbol", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.token_symbol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenContract(); !ok {
		return &ValidationError{Name: "token_contract", err: errors.New(`ent: missing required field "OnchainDeposit.token_contract"`)}
	}
	if v, ok := _c.mutation.TokenContract(); ok {
		if err := onchaindeposit.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.token_contract": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TxHash(); !ok {
		return &ValidationError{Name: "tx_hash", err: errors.New(`ent: missing required field "OnchainDeposit.tx_hash"`)}
	}
	if v, ok := _c.mutation.TxHash(); ok {
		if err := onchaindeposit.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.tx_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LogIndex(); !ok {
		return &ValidationError{Name: "log_index", err: errors.New(`ent: missing required field "OnchainDeposit.log_index"`)}
	}
	if _, ok := _c.mutation.BlockNumber(); !ok {
		return &ValidationError{Name: "block_number", err: errors.New(`ent: missing required field "OnchainDeposit.block_number"`)}
	}
	if _, ok := _c.mutation.BlockHash(); !ok {
		return &ValidationError{Name: "block_hash", err: errors.New(`ent: missing required field "OnchainDeposit.block_hash"`)}
	}
	if v, ok := _c.mutation.BlockHash(); ok {
		if err := onchaindeposit.BlockHashValidator(v); err != nil {
			return &ValidationError{Name: "block_hash", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.block_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		return &ValidationError{Name: "from_address", err: errors.New(`ent: missing required field "OnchainDeposit.from_address"`)}
	}
	if v, ok := _c.mutation.FromAddress(); ok {
		if err := onchaindeposit.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.from_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToAddress(); !ok {
		return &ValidationError{Name: "to_address", err: errors.New(`ent: missing required field "OnchainDeposit.to_address"`)}
	}
	if v, ok := _c.mutation.ToAddress(); ok {
		if err := onchaindeposit.ToAddressValidator(v); err != nil {
			return &ValidationError{Name: "to_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.to_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountRaw(); !ok {
		return &ValidationError{Name: "amount_raw", err: errors.New(`ent: missing required field "OnchainDeposit.amount_raw"`)}
	}
	if v, ok := _c.mutation.AmountRaw(); ok {
		if err := onchaindeposit.AmountRawValidator(v); err != nil {
			return &ValidationError{Name: "amount_raw", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.amount_raw": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountCredit(); !ok {
		return &ValidationError{Name: "amount_credit", err: errors.New(`ent: missing required field "OnchainDeposit.amount_credit"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OnchainDeposit.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := onchaindeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.status": %w`, err)}
		}
	}
	return nil
}

func (_c *OnchainDepositCreate) sqlSave(ctx context.Context) (*OnchainDeposit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OnchainDepositCreate) createSpec() (*OnchainDeposit, *sqlgraph.CreateSpec) {
	var (
		_node = &OnchainDeposit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(onchaindeposit.Table, sqlgraph.NewFieldSpec(onchaindeposit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(onchaindeposit.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(onchaindeposit.FieldChain, field.TypeString, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.TokenSymbol(); ok {
		_spec.SetField(onchaindeposit.FieldTokenSymbol, field.TypeString, value)
		_node.TokenSymbol = value
	}
	if value, ok := _c.mutation.TokenContract(); ok {
		_spec.SetField(onchaindeposit.FieldTokenContract, field.TypeString, value)
		_node.TokenContract = value
	}
	if value, ok := _c.mutation.TxHash(); ok {
		_spec.SetField(onchaindeposit.FieldTxHash, field.TypeString, value)
		_node.TxHash = value
	}
	if value, ok := _c.mutation.LogIndex(); ok {
		_spec.SetField(onchaindeposit.FieldLogIndex, field.TypeInt64, value)
		_node.LogIndex = value
	}
	if value, ok := _c.mutation.BlockNumber(); ok {
		_spec.SetField(onchaindeposit.FieldBlockNumber, field.TypeInt64, value)
		_node.BlockNumber = value
	}
	if value, ok := _c.mutation.BlockHash(); ok {
		_spec.SetField(onchaindeposit.FieldBlockHash, field.TypeString, value)
		_node.BlockHash = value
	}
	if value, ok := _c.mutation.FromAddress(); ok {
		_spec.SetField(onchaindeposit.FieldFromAddress, field.TypeString, value)
		_node.FromAddress = value
	}
	if value, ok := _c.mutation.ToAddress(); ok {
		_spec.SetField(onchaindeposit.FieldToAddress, field.TypeString, value)
		_node.ToAddress = value
	}
	if value, ok := _c.mutation.AmountRaw(); ok {
		_spec.SetField(onchaindeposit.FieldAmountRaw, field.TypeString, value)
		_node.AmountRaw = value
	}
	if value, ok := _c.mutation.AmountCredit(); ok {
		_spec.SetField(onchaindeposit.FieldAmountCredit, field.TypeFloat64, value)
		_node.AmountCredit = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(onchaindeposit.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreditedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreditedAt, field.TypeTime, value)
		_node.CreditedAt = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(onchaindeposit.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OnchainDeposit.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnchainDepositUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OnchainDepositCreate) OnConflict(opts ...sql.ConflictOption) *OnchainDepositUpsertOne {
	_c.conflict = opts
	return &OnchainDepositUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OnchainDepositCreate) OnConflictColumns(columns ...string) *OnchainDepositUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OnchainDepositUpsertOne{
		create: _c,
	}
}

type (
	// OnchainDepositUpsertOne is the builder for "upsert"-ing
	//  one OnchainDeposit node.
	OnchainDepositUpsertOne struct {
		create *OnchainDepositCreate
	}

	// OnchainDepositUpsert is the "OnConflict" setter.
	OnchainDepositUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositUpsert) SetUpdatedAt(v time.Time) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateUpdatedAt() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OnchainDepositUpsert) SetUserID(v int64) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateUserID() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OnchainDepositUpsert) AddUserID(v int64) *OnchainDepositUpsert {
	u.Add(onchaindeposit.FieldUserID, v)
	return u
}

// SetChain sets the "chain" field.
func (u *OnchainDepositUpsert) SetChain(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldChain, v)
	return u
}

// UpdateChain sets the "chain" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateChain() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldChain)
	return u
}

// SetTokenSymbol sets the "token_symbol" field.
func (u *OnchainDepositUpsert) SetTokenSymbol(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldTokenSymbol, v)
	return u
}

// UpdateTokenSymbol sets the "token_symbol" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateTokenSymbol() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldTokenSymbol)
	return u
}

// SetTokenContract sets the "token_contract" field.
func (u *OnchainDepositUpsert) SetTokenContract(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldTokenContract, v)
	return u
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateTokenContract() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldTokenContract)
	return u
}

// SetTxHash sets the "tx_hash" field.
func (u *OnchainDepositUpsert) SetTxHash(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldTxHash, v)
	return u
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateTxHash() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldTxHash)
	return u
}

// SetLogIndex sets the "log_index" field.
func (u *OnchainDepositUpsert) SetLogIndex(v int64) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldLogIndex, v)
	return u
}

// UpdateLogIndex sets the "log_index" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateLogIndex() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldLogIndex)
	return u
}

// AddLogIndex adds v to the "log_index" field.
func (u *OnchainDepositUpsert) AddLogIndex(v int64) *OnchainDepositUpsert {
	u.Add(onchaindeposit.FieldLogIndex, v)
	return u
}

// SetBlockNumber sets the "block_number" field.
func (u *OnchainDepositUpsert) SetBlockNumber(v int64) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldBlockNumber, v)
	return u
}

// UpdateBlockNumber sets the "block_number" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateBlockNumber() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldBlockNumber)
	return u
}

// AddBlockNumber adds v to the "block_number" field.
func (u *OnchainDepositUpsert) AddBlockNumber(v int64) *OnchainDepositUpsert {
	u.Add(onchaindeposit.FieldBlockNumber, v)
	return u
}

// SetBlockHash sets the "block_hash" field.
func (u *OnchainDepositUpsert) SetBlockHash(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldBlockHash, v)
	return u
}

// UpdateBlockHash sets the "block_hash" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateBlockHash() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldBlockHash)
	return u
}

// SetFromAddress sets the "from_address" field.
func (u *OnchainDepositUpsert) SetFromAddress(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldFromAddress, v)
	return u
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateFromAddress() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldFromAddress)
	return u
}

// SetToAddress sets the "to_address" field.
func (u *OnchainDepositUpsert) SetToAddress(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldToAddress, v)
	return u
}

// UpdateToAddress sets the "to_address" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateToAddress() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldToAddress)
	return u
}

// SetAmountRaw sets the "amount_raw" field.
func (u *OnchainDepositUpsert) SetAmountRaw(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldAmountRaw, v)
	return u
}

// UpdateAmountRaw sets the "amount_raw" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateAmountRaw() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldAmountRaw)
	return u
}

// SetAmountCredit sets the "amount_credit" field.
func (u *OnchainDepositUpsert) SetAmountCredit(v float64) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldAmountCredit, v)
	return u
}

// UpdateAmountCredit sets the "amount_credit" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateAmountCredit() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldAmountCredit)
	return u
}

// AddAmountCredit adds v to the "amount_credit" field.
func (u *OnchainDepositUpsert) AddAmountCredit(v float64) *OnchainDepositUpsert {
	u.Add(onchaindeposit.FieldAmountCredit, v)
	return u
}

// SetStatus sets the "status" field.
func (u *OnchainDepositUpsert) SetStatus(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateStatus() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldStatus)
	return u
}

// SetCreditedAt sets the "credited_at" field.
func (u *OnchainDepositUpsert) SetCreditedAt(v time.Time) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldCreditedAt, v)
	return u
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateCreditedAt() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldCreditedAt)
	return u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *OnchainDepositUpsert) ClearCreditedAt() *OnchainDepositUpsert {
	u.SetNull(onchaindeposit.FieldCreditedAt)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *OnchainDepositUpsert) SetErrorMessage(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateErrorMessage() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *OnchainDepositUpsert) ClearErrorMessage() *OnchainDepositUpsert {
	u.SetNull(onchaindeposit.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OnchainDepositUpsertOne) UpdateNewValues() *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(onchaindeposit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OnchainDepositUpsertOne) Ignore() *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnchainDepositUpsertOne) DoNothing() *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnchainDepositCreate.OnConflict
// documentation for more info.
func (u *OnchainDepositUpsertOne) Update(set func(*OnchainDepositUpsert)) *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnchainDepositUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositUpsertOne) SetUpdatedAt(v time.Time) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateUpdatedAt() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OnchainDepositUpsertOne) SetUserID(v int64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OnchainDepositUpsertOne) AddUserID(v int64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateUserID() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateUserID()
	})
}

// SetChain sets the "chain" field.
func (u *OnchainDepositUpsertOne) SetChain(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetChain(v)
	})
}

// UpdateChain sets the "chain" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateChain() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateChain()
	})
}

// SetTokenSymbol sets the "token_symbol" field.
func (u *OnchainDepositUpsertOne) SetTokenSymbol(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetTokenSymbol(v)
	})
}

// UpdateTokenSymbol sets the "token_symbol" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateTokenSymbol() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateTokenSymbol()
	})
}

// SetTokenContract sets the "token_contract" field.
func (u *OnchainDepositUpsertOne) SetTokenContract(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetTokenContract(v)
	})
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateTokenContract() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateTokenContract()
	})
}

// SetTxHash sets the "tx_hash" field.
func (u *OnchainDepositUpsertOne) SetTxHash(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateTxHash() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateTxHash()
	})
}

// SetLogIndex sets the "log_index" field.
func (u *OnchainDepositUpsertOne) SetLogIndex(v int64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetLogIndex(v)
	})
}

// AddLogIndex adds v to the "log_index" field.
func (u *OnchainDepositUpsertOne) AddLogIndex(v int64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddLogIndex(v)
	})
}

// UpdateLogIndex sets the "log_index" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateLogIndex() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateLogIndex()
	})
}

// SetBlockNumber sets the "block_number" field.
func (u *OnchainDepositUpsertOne) SetBlockNumber(v int64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetBlockNumber(v)
	})
}

// AddBlockNumber adds v to the "block_number" field.
func (u *OnchainDepositUpsertOne) AddBlockNumber(v int64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddBlockNumber(v)
	})
}

// UpdateBlockNumber sets the "block_number" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateBlockNumber() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateBlockNumber()
	})
}

// SetBlockHash sets the "block_hash" field.
func (u *OnchainDepositUpsertOne) SetBlockHash(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetBlockHash(v)
	})
}

// UpdateBlockHash sets the "block_hash" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateBlockHash() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateBlockHash()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *OnchainDepositUpsertOne) SetFromAddress(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateFromAddress() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateFromAddress()
	})
}

// SetToAddress sets the "to_address" field.
func (u *OnchainDepositUpsertOne) SetToAddress(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetToAddress(v)
	})
}

// UpdateToAddress sets the "to_address" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateToAddress() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateToAddress()
	})
}

// SetAmountRaw sets the "amount_raw" field.
func (u *OnchainDepositUpsertOne) SetAmountRaw(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetAmountRaw(v)
	})
}

// UpdateAmountRaw sets the "amount_raw" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateAmountRaw() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateAmountRaw()
	})
}

// SetAmountCredit sets the "amount_credit" field.
func (u *OnchainDepositUpsertOne) SetAmountCredit(v float64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetAmountCredit(v)
	})
}

// AddAmountCredit adds v to the "amount_credit" field.
func (u *OnchainDepositUpsertOne) AddAmountCredit(v float64) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddAmountCredit(v)
	})
}

// UpdateAmountCredit sets the "amount_credit" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateAmountCredit() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateAmountCredit()
	})
}

// SetStatus sets the "status" field.
func (u *OnchainDepositUpsertOne) SetStatus(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateStatus() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateStatus()
	})
}

// SetCreditedAt sets the "credited_at" field.
func (u *OnchainDepositUpsertOne) SetCreditedAt(v time.Time) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetCreditedAt(v)
	})
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateCreditedAt() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateCreditedAt()
	})
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *OnchainDepositUpsertOne) ClearCreditedAt() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearCreditedAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *OnchainDepositUpsertOne) SetErrorMessage(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateErrorMessage() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *OnchainDepositUpsertOne) ClearErrorMessage() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *OnchainDepositUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnchainDepositCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnchainDepositUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OnchainDepositUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OnchainDepositUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OnchainDepositCreateBulk is the builder for creating many OnchainDeposit entities in bulk.
type OnchainDepositCreateBulk struct {
	config
	err      error
	builders []*OnchainDepositCreate
	conflict []sql.ConflictOption
}

// Save creates the OnchainDeposit entities in the database.
func (_c *OnchainDepositCreateBulk) Save(ctx context.Context) ([]*OnchainDeposit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OnchainDeposit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OnchainDepositMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OnchainDepositCreateBulk) SaveX(ctx context.Context) []*OnchainDeposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OnchainDepositCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OnchainDepositCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OnchainDeposit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnchainDepositUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OnchainDepositCreateBulk) OnConflict(opts ...sql.ConflictOption) *OnchainDepositUpsertBulk {
	_c.conflict = opts
	return &OnchainDepositUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OnchainDepositCreateBulk) OnConflictColumns(columns ...string) *OnchainDepositUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OnchainDepositUpsertBulk{
		create: _c,
	}
}

// OnchainDepositUpsertBulk is the builder for "upsert"-ing
// a bulk of OnchainDeposit nodes.
type OnchainDepositUpsertBulk struct {
	create *OnchainDepositCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OnchainDepositUpsertBulk) UpdateNewValues() *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(onchaindeposit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OnchainDepositUpsertBulk) Ignore() *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnchainDepositUpsertBulk) DoNothing() *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnchainDepositCreateBulk.OnConflict
// documentation for more info.
func (u *OnchainDepositUpsertBulk) Update(set func(*OnchainDepositUpsert)) *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnchainDepositUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositUpsertBulk) SetUpdatedAt(v time.Time) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateUpdatedAt() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OnchainDepositUpsertBulk) SetUserID(v int64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OnchainDepositUpsertBulk) AddUserID(v int64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateUserID() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateUserID()
	})
}

// SetChain sets the "chain" field.
func (u *OnchainDepositUpsertBulk) SetChain(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetChain(v)
	})
}

// UpdateChain sets the "chain" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateChain() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateChain()
	})
}

// SetTokenSymbol sets the "token_symbol" field.
func (u *OnchainDepositUpsertBulk) SetTokenSymbol(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetTokenSymbol(v)
	})
}

// UpdateTokenSymbol sets the "token_symbol" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateTokenSymbol() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateTokenSymbol()
	})
}

// SetTokenContract sets the "token_contract" field.
func (u *OnchainDepositUpsertBulk) SetTokenContract(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetTokenContract(v)
	})
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateTokenContract() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateTokenContract()
	})
}

// SetTxHash sets the "tx_hash" field.
func (u *OnchainDepositUpsertBulk) SetTxHash(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateTxHash() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateTxHash()
	})
}

// SetLogIndex sets the "log_index" field.
func (u *OnchainDepositUpsertBulk) SetLogIndex(v int64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetLogIndex(v)
	})
}

// AddLogIndex adds v to the "log_index" field.
func (u *OnchainDepositUpsertBulk) AddLogIndex(v int64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddLogIndex(v)
	})
}

// UpdateLogIndex sets the "log_index" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateLogIndex() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateLogIndex()
	})
}

// SetBlockNumber sets the "block_number" field.
func (u *OnchainDepositUpsertBulk) SetBlockNumber(v int64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetBlockNumber(v)
	})
}

// AddBlockNumber adds v to the "block_number" field.
func (u *OnchainDepositUpsertBulk) AddBlockNumber(v int64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddBlockNumber(v)
	})
}

// UpdateBlockNumber sets the "block_number" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateBlockNumber() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateBlockNumber()
	})
}

// SetBlockHash sets the "block_hash" field.
func (u *OnchainDepositUpsertBulk) SetBlockHash(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetBlockHash(v)
	})
}

// UpdateBlockHash sets the "block_hash" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateBlockHash() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateBlockHash()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *OnchainDepositUpsertBulk) SetFromAddress(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateFromAddress() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateFromAddress()
	})
}

// SetToAddress sets the "to_address" field.
func (u *OnchainDepositUpsertBulk) SetToAddress(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetToAddress(v)
	})
}

// UpdateToAddress sets the "to_address" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateToAddress() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateToAddress()
	})
}

// SetAmountRaw sets the "amount_raw" field.
func (u *OnchainDepositUpsertBulk) SetAmountRaw(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetAmountRaw(v)
	})
}

// UpdateAmountRaw sets the "amount_raw" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateAmountRaw() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateAmountRaw()
	})
}

// SetAmountCredit sets the "amount_credit" field.
func (u *OnchainDepositUpsertBulk) SetAmountCredit(v float64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetAmountCredit(v)
	})
}

// AddAmountCredit adds v to the "amount_credit" field.
func (u *OnchainDepositUpsertBulk) AddAmountCredit(v float64) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddAmountCredit(v)
	})
}

// UpdateAmountCredit sets the "amount_credit" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateAmountCredit() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateAmountCredit()
	})
}

// SetStatus sets the "status" field.
func (u *OnchainDepositUpsertBulk) SetStatus(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateStatus() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateStatus()
	})
}

// SetCreditedAt sets the "credited_at" field.
func (u *OnchainDepositUpsertBulk) SetCreditedAt(v time.Time) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetCreditedAt(v)
	})
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateCreditedAt() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateCreditedAt()
	})
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *OnchainDepositUpsertBulk) ClearCreditedAt() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearCreditedAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *OnchainDepositUpsertBulk) SetErrorMessage(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateErrorMessage() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *OnchainDepositUpsertBulk) ClearErrorMessage() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *OnchainDepositUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OnchainDepositCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnchainDepositCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnchainDepositUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
