// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchaindepositscanstate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OnchainDepositScanStateUpdate is the builder for updating OnchainDepositScanState entities.
type OnchainDepositScanStateUpdate struct {
	config
	hooks    []Hook
	mutation *OnchainDepositScanStateMutation
}

// Where appends a list predicates to the OnchainDepositScanStateUpdate builder.
func (_u *OnchainDepositScanStateUpdate) Where(ps ...predicate.OnchainDepositScanState) *OnchainDepositScanStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OnchainDepositScanStateUpdate) SetUpdatedAt(v time.Time) *OnchainDepositScanStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChain sets the "chain" field.
func (_u *OnchainDepositScanStateUpdate) SetChain(v string) *OnchainDepositScanStateUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *OnchainDepositScanStateUpdate) SetNillableChain(v *string) *OnchainDepositScanStateUpdate {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (_u *OnchainDepositScanStateUpdate) SetLastScannedBlock(v int64) *OnchainDepositScanStateUpdate {
	_u.mutation.ResetLastScannedBlock()
	_u.mutation.SetLastScannedBlock(v)
	return _u
}

// SetNillableLastScannedBlock sets the "last_scanned_block" field if the given value is not nil.
func (_u *OnchainDepositScanStateUpdate) SetNillableLastScannedBlock(v *int64) *OnchainDepositScanStateUpdate {
	if v != nil {
		_u.SetLastScannedBlock(*v)
	}
	return _u
}

// AddLastScannedBlock adds value to the "last_scanned_block" field.
func (_u *OnchainDepositScanStateUpdate) AddLastScannedBlock(v int64) *OnchainDepositScanStateUpdate {
	_u.mutation.AddLastScannedBlock(v)
	return _u
}

// Mutation returns the OnchainDepositScanStateMutation object of the builder.
func (_u *OnchainDepositScanStateUpdate) Mutation() *OnchainDepositScanStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OnchainDepositScanStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OnchainDepositScanStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OnchainDepositScanStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OnchainDepositScanStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OnchainDepositScanStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := onchaindepositscanstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OnchainDepositScanStateUpdate) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := onchaindepositscanstate.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "OnchainDepositScanState.chain": %w`, err)}
		}
	}
	return nil
}

func (_u *OnchainDepositScanStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onchaindepositscanstate.Table, onchaindepositscanstate.Columns, sqlgraph.NewFieldSpec(onchaindepositscanstate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindepositscanstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(onchaindepositscanstate.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScannedBlock(); ok {
		_spec.SetField(onchaindepositscanstate.FieldLastScannedBlock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastScannedBlock(); ok {
		_spec.AddField(onchaindepositscanstate.FieldLastScannedBlock, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onchaindepositscanstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OnchainDepositScanStateUpdateOne is the builder for updating a single OnchainDepositScanState entity.
type OnchainDepositScanStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OnchainDepositScanStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OnchainDepositScanStateUpdateOne) SetUpdatedAt(v time.Time) *OnchainDepositScanStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChain sets the "chain" field.
func (_u *OnchainDepositScanStateUpdateOne) SetChain(v string) *OnchainDepositScanStateUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *OnchainDepositScanStateUpdateOne) SetNillableChain(v *string) *OnchainDepositScanStateUpdateOne {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (_u *OnchainDepositScanStateUpdateOne) SetLastScannedBlock(v int64) *OnchainDepositScanStateUpdateOne {
	_u.mutation.ResetLastScannedBlock()
	_u.mutation.SetLastScannedBlock(v)
	return _u
}

// SetNillableLastScannedBlock sets the "last_scanned_block" field if the given value is not nil.
func (_u *OnchainDepositScanStateUpdateOne) SetNillableLastScannedBlock(v *int64) *OnchainDepositScanStateUpdateOne {
	if v != nil {
		_u.SetLastScannedBlock(*v)
	}
	return _u
}

// AddLastScannedBlock adds value to the "last_scanned_block" field.
func (_u *OnchainDepositScanStateUpdateOne) AddLastScannedBlock(v int64) *OnchainDepositScanStateUpdateOne {
	_u.mutation.AddLastScannedBlock(v)
	return _u
}

// Mutation returns the OnchainDepositScanStateMutation object of the builder.
func (_u *OnchainDepositScanStateUpdateOne) Mutation() *OnchainDepositScanStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the OnchainDepositScanStateUpdate builder.
func (_u *OnchainDepositScanStateUpdateOne) Where(ps ...predicate.OnchainDepositScanState) *OnchainDepositScanStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OnchainDepositScanStateUpdateOne) Select(field string, fields ...string) *OnchainDepositScanStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OnchainDepositScanState entity.
func (_u *OnchainDepositScanStateUpdateOne) Save(ctx context.Context) (*OnchainDepositScanState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OnchainDepositScanStateUpdateOne) SaveX(ctx context.Context) *OnchainDepositScanState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OnchainDepositScanStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OnchainDepositScanStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OnchainDepositScanStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := onchaindepositscanstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OnchainDepositScanStateUpdateOne) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := onchaindepositscanstate.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "OnchainDepositScanState.chain": %w`, err)}
		}
	}
	return nil
}

func (_u *OnchainDepositScanStateUpdateOne) sqlSave(ctx context.Context) (_node *OnchainDepositScanState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onchaindepositscanstate.Table, onchaindepositscanstate.Columns, sqlgraph.NewFieldSpec(onchaindepositscanstate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OnchainDepositScanState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onchaindepositscanstate.FieldID)
		for _, f := range fields {
			if !onchaindepositscanstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != onchaindepositscanstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindepositscanstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(onchaindepositscanstate.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScannedBlock(); ok {
		_spec.SetField(onchaindepositscanstate.FieldLastScannedBlock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastScannedBlock(); ok {
		_spec.AddField(onchaindepositscanstate.FieldLastScannedBlock, field.TypeInt64, value)
	}
	_node = &OnchainDepositScanState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onchaindepositscanstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
