// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchaindepositscanstate"
)

// OnchainDepositScanStateCreate is the builder for creating a OnchainDepositScanState entity.
type OnchainDepositScanStateCreate struct {
	config
	mutation *OnchainDepositScanStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OnchainDepositScanStateCreate) SetCreatedAt(v time.Time) *OnchainDepositScanStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OnchainDepositScanStateCreate) SetNillableCreatedAt(v *time.Time) *OnchainDepositScanStateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OnchainDepositScanStateCreate) SetUpdatedAt(v time.Time) *OnchainDepositScanStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OnchainDepositScanStateCreate) SetNillableUpdatedAt(v *time.Time) *OnchainDepositScanStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChain sets the "chain" field.
func (_c *OnchainDepositScanStateCreate) SetChain(v string) *OnchainDepositScanStateCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (_c *OnchainDepositScanStateCreate) SetLastScannedBlock(v int64) *OnchainDepositScanStateCreate {
	_c.mutation.SetLastScannedBlock(v)
	return _c
}

// SetNillableLastScannedBlock sets the "last_scanned_block" field if the given value is not nil.
func (_c *OnchainDepositScanStateCreate) SetNillableLastScannedBlock(v *int64) *OnchainDepositScanStateCreate {
	if v != nil {
		_c.SetLastScannedBlock(*v)
	}
	return _c
}

// Mutation returns the OnchainDepositScanStateMutation object of the builder.
func (_c *OnchainDepositScanStateCreate) Mutation() *OnchainDepositScanStateMutation {
	return _c.mutation
}

// Save creates the OnchainDepositScanState in the database.
func (_c *OnchainDepositScanStateCreate) Save(ctx context.Context) (*OnchainDepositScanState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OnchainDepositScanStateCreate) SaveX(ctx context.Context) *OnchainDepositScanState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OnchainDepositScanStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OnchainDepositScanStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OnchainDepositScanStateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := onchaindepositscanstate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := onchaindepositscanstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LastScannedBlock(); !ok {
		v := onchaindepositscanstate.DefaultLastScannedBlock
		_c.mutation.SetLastScannedBlock(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OnchainDepositScanStateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OnchainDepositScanState.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OnchainDepositScanState.updated_at"`)}
	}
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "OnchainDepositScanState.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := onchaindepositscanstate.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "OnchainDepositScanState.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastScannedBlock(); !ok {
		return &ValidationError{Name: "last_scanned_block", err: errors.New(`ent: missing required field "OnchainDepositScanState.last_scanned_block"`)}
	}
	return nil
}

func (_c *OnchainDepositScanStateCreate) sqlSave(ctx context.Context) (*OnchainDepositScanState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OnchainDepositScanStateCreate) createSpec() (*OnchainDepositScanState, *sqlgraph.CreateSpec) {
	var (
		_node = &OnchainDepositScanState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(onchaindepositscanstate.Table, sqlgraph.NewFieldSpec(onchaindepositscanstate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(onchaindepositscanstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindepositscanstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(onchaindepositscanstate.FieldChain, field.TypeString, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.LastScannedBlock(); ok {
		_spec.SetField(onchaindepositscanstate.FieldLastScannedBlock, field.TypeInt64, value)
		_node.LastScannedBlock = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OnchainDepositScanState.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnchainDepositScanStateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OnchainDepositScanStateCreate) OnConflict(opts ...sql.ConflictOption) *OnchainDepositScanStateUpsertOne {
	_c.conflict = opts
	return &OnchainDepositScanStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OnchainDepositScanState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OnchainDepositScanStateCreate) OnConflictColumns(columns ...string) *OnchainDepositScanStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OnchainDepositScanStateUpsertOne{
		create: _c,
	}
}

type (
	// OnchainDepositScanStateUpsertOne is the builder for "upsert"-ing
	//  one OnchainDepositScanState node.
	OnchainDepositScanStateUpsertOne struct {
		create *OnchainDepositScanStateCreate
	}

	// OnchainDepositScanStateUpsert is the "OnConflict" setter.
	OnchainDepositScanStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositScanStateUpsert) SetUpdatedAt(v time.Time) *OnchainDepositScanStateUpsert {
	u.Set(onchaindepositscanstate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsert) UpdateUpdatedAt() *OnchainDepositScanStateUpsert {
	u.SetExcluded(onchaindepositscanstate.FieldUpdatedAt)
	return u
}

// SetChain sets the "chain" field.
func (u *OnchainDepositScanStateUpsert) SetChain(v string) *OnchainDepositScanStateUpsert {
	u.Set(onchaindepositscanstate.FieldChain, v)
	return u
}

// UpdateChain sets the "chain" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsert) UpdateChain() *OnchainDepositScanStateUpsert {
	u.SetExcluded(onchaindepositscanstate.FieldChain)
	return u
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (u *OnchainDepositScanStateUpsert) SetLastScannedBlock(v int64) *OnchainDepositScanStateUpsert {
	u.Set(onchaindepositscanstate.FieldLastScannedBlock, v)
	return u
}

// UpdateLastScannedBlock sets the "last_scanned_block" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsert) UpdateLastScannedBlock() *OnchainDepositScanStateUpsert {
	u.SetExcluded(onchaindepositscanstate.FieldLastScannedBlock)
	return u
}

// AddLastScannedBlock adds v to the "last_scanned_block" field.
func (u *OnchainDepositScanStateUpsert) AddLastScannedBlock(v int64) *OnchainDepositScanStateUpsert {
	u.Add(onchaindepositscanstate.FieldLastScannedBlock, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OnchainDepositScanState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OnchainDepositScanStateUpsertOne) UpdateNewValues() *OnchainDepositScanStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(onchaindepositscanstate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OnchainDepositScanState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OnchainDepositScanStateUpsertOne) Ignore() *OnchainDepositScanStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnchainDepositScanStateUpsertOne) DoNothing() *OnchainDepositScanStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnchainDepositScanStateCreate.OnConflict
// documentation for more info.
func (u *OnchainDepositScanStateUpsertOne) Update(set func(*OnchainDepositScanStateUpsert)) *OnchainDepositScanStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnchainDepositScanStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositScanStateUpsertOne) SetUpdatedAt(v time.Time) *OnchainDepositScanStateUpsertOne {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsertOne) UpdateUpdatedAt() *OnchainDepositScanStateUpsertOne {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetChain sets the "chain" field.
func (u *OnchainDepositScanStateUpsertOne) SetChain(v string) *OnchainDepositScanStateUpsertOne {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.SetChain(v)
	})
}

// UpdateChain sets the "chain" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsertOne) UpdateChain() *OnchainDepositScanStateUpsertOne {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.UpdateChain()
	})
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (u *OnchainDepositScanStateUpsertOne) SetLastScannedBlock(v int64) *OnchainDepositScanStateUpsertOne {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.SetLastScannedBlock(v)
	})
}

// AddLastScannedBlock adds v to the "last_scanned_block" field.
func (u *OnchainDepositScanStateUpsertOne) AddLastScannedBlock(v int64) *OnchainDepositScanStateUpsertOne {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.AddLastScannedBlock(v)
	})
}

// UpdateLastScannedBlock sets the "last_scanned_block" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsertOne) UpdateLastScannedBlock() *OnchainDepositScanStateUpsertOne {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.UpdateLastScannedBlock()
	})
}

// Exec executes the query.
func (u *OnchainDepositScanStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnchainDepositScanStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnchainDepositScanStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OnchainDepositScanStateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OnchainDepositScanStateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OnchainDepositScanStateCreateBulk is the builder for creating many OnchainDepositScanState entities in bulk.
type OnchainDepositScanStateCreateBulk struct {
	config
	err      error
	builders []*OnchainDepositScanStateCreate
	conflict []sql.ConflictOption
}

// Save creates the OnchainDepositScanState entities in the database.
func (_c *OnchainDepositScanStateCreateBulk) Save(ctx context.Context) ([]*OnchainDepositScanState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OnchainDepositScanState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OnchainDepositScanStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OnchainDepositScanStateCreateBulk) SaveX(ctx context.Context) []*OnchainDepositScanState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OnchainDepositScanStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OnchainDepositScanStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OnchainDepositScanState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnchainDepositScanStateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OnchainDepositScanStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *OnchainDepositScanStateUpsertBulk {
	_c.conflict = opts
	return &OnchainDepositScanStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OnchainDepositScanState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OnchainDepositScanStateCreateBulk) OnConflictColumns(columns ...string) *OnchainDepositScanStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OnchainDepositScanStateUpsertBulk{
		create: _c,
	}
}

// OnchainDepositScanStateUpsertBulk is the builder for "upsert"-ing
// a bulk of OnchainDepositScanState nodes.
type OnchainDepositScanStateUpsertBulk struct {
	create *OnchainDepositScanStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OnchainDepositScanState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OnchainDepositScanStateUpsertBulk) UpdateNewValues() *OnchainDepositScanStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(onchaindepositscanstate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OnchainDepositScanState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OnchainDepositScanStateUpsertBulk) Ignore() *OnchainDepositScanStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnchainDepositScanStateUpsertBulk) DoNothing() *OnchainDepositScanStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnchainDepositScanStateCreateBulk.OnConflict
// documentation for more info.
func (u *OnchainDepositScanStateUpsertBulk) Update(set func(*OnchainDepositScanStateUpsert)) *OnchainDepositScanStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnchainDepositScanStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositScanStateUpsertBulk) SetUpdatedAt(v time.Time) *OnchainDepositScanStateUpsertBulk {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsertBulk) UpdateUpdatedAt() *OnchainDepositScanStateUpsertBulk {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetChain sets the "chain" field.
func (u *OnchainDepositScanStateUpsertBulk) SetChain(v string) *OnchainDepositScanStateUpsertBulk {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.SetChain(v)
	})
}

// UpdateChain sets the "chain" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsertBulk) UpdateChain() *OnchainDepositScanStateUpsertBulk {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.UpdateChain()
	})
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (u *OnchainDepositScanStateUpsertBulk) SetLastScannedBlock(v int64) *OnchainDepositScanStateUpsertBulk {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.SetLastScannedBlock(v)
	})
}

// AddLastScannedBlock adds v to the "last_scanned_block" field.
func (u *OnchainDepositScanStateUpsertBulk) AddLastScannedBlock(v int64) *OnchainDepositScanStateUpsertBulk {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.AddLastScannedBlock(v)
	})
}

// UpdateLastScannedBlock sets the "last_scanned_block" field to the value that was provided on create.
func (u *OnchainDepositScanStateUpsertBulk) UpdateLastScannedBlock() *OnchainDepositScanStateUpsertBulk {
	return u.Update(func(s *OnchainDepositScanStateUpsert) {
		s.UpdateLastScannedBlock()
	})
}

// Exec executes the query.
func (u *OnchainDepositScanStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OnchainDepositScanStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnchainDepositScanStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnchainDepositScanStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
