// Code generated by ent, DO NOT EDIT.

package onchaindeposit

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the onchaindeposit type in the database.
	Label = "onchain_deposit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldChain holds the string denoting the chain field in the database.
	FieldChain = "chain"
	// FieldTokenSymbol holds the string denoting the token_symbol field in the database.
	FieldTokenSymbol = "token_symbol"
	// FieldTokenContract holds the string denoting the token_contract field in the database.
	FieldTokenContract = "token_contract"
	// FieldTxHash holds the string denoting the tx_hash field in the database.
	FieldTxHash = "tx_hash"
	// FieldLogIndex holds the string denoting the log_index field in the database.
	FieldLogIndex = "log_index"
	// FieldBlockNumber holds the string denoting the block_number field in the database.
	FieldBlockNumber = "block_number"
	// FieldBlockHash holds the string denoting the block_hash field in the database.
	FieldBlockHash = "block_hash"
	// FieldFromAddress holds the string denoting the from_address field in the database.
	FieldFromAddress = "from_address"
	// FieldToAddress holds the string denoting the to_address field in the database.
	FieldToAddress = "to_address"
	// FieldAmountRaw holds the string denoting the amount_raw field in the database.
	FieldAmountRaw = "amount_raw"
	// FieldAmountCredit holds the string denoting the amount_credit field in the database.
	FieldAmountCredit = "amount_credit"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreditedAt holds the string denoting the credited_at field in the database.
	FieldCreditedAt = "credited_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// Table holds the table name of the onchaindeposit in the database.
	Table = "onchain_deposits"
)

// Columns holds all SQL columns for onchaindeposit fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldChain,
	FieldTokenSymbol,
	FieldTokenContract,
	FieldTxHash,
	FieldLogIndex,
	FieldBlockNumber,
	FieldBlockHash,
	FieldFromAddress,
	FieldToAddress,
	FieldAmountRaw,
	FieldAmountCredit,
	FieldStatus,
	FieldCreditedAt,
	FieldErrorMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	ChainValidator func(string) error
	// TokenSymbolValidator is a validator for the "token_symbol" field. It is called by the builders before save.
	TokenSymbolValidator func(string) error
	// TokenContractValidator is a validator for the "token_contract" field. It is called by the builders before save.
	TokenContractValidator func(string) error
	// TxHashValidator is a validator for the "tx_hash" field. It is called by the builders before save.
	TxHashValidator func(string) error
	// BlockHashValidator is a validator for the "block_hash" field. It is called by the builders before save.
	BlockHashValidator func(string) error
	// FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	FromAddressValidator func(string) error
	// ToAddressValidator is a validator for the "to_address" field. It is called by the builders before save.
	ToAddressValidator func(string) error
	// AmountRawValidator is a validator for the "amount_raw" field. It is called by the builders before save.
	AmountRawValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the OnchainDeposit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByChain orders the results by the chain field.
func ByChain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChain, opts...).ToFunc()
}

// ByTokenSymbol orders the results by the token_symbol field.
func ByTokenSymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenSymbol, opts...).ToFunc()
}

// ByTokenContract orders the results by the token_contract field.
func ByTokenContract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenContract, opts...).ToFunc()
}

// ByTxHash orders the results by the tx_hash field.
func ByTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxHash, opts...).ToFunc()
}

// ByLogIndex orders the results by the log_index field.
func ByLogIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogIndex, opts...).ToFunc()
}

// ByBlockNumber orders the results by the block_number field.
func ByBlockNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockNumber, opts...).ToFunc()
}

// ByBlockHash orders the results by the block_hash field.
func ByBlockHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockHash, opts...).ToFunc()
}

// ByFromAddress orders the results by the from_address field.
func ByFromAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAddress, opts...).ToFunc()
}

// ByToAddress orders the results by the to_address field.
func ByToAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToAddress, opts...).ToFunc()
}

// ByAmountRaw orders the results by the amount_raw field.
func ByAmountRaw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountRaw, opts...).ToFunc()
}

// ByAmountCredit orders the results by the amount_credit field.
func ByAmountCredit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCredit, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreditedAt orders the results by the credited_at field.
func ByCreditedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditedAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}
