// Code generated by ent, DO NOT EDIT.

package onchaindeposit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldUserID, v))
}

// Chain applies equality check predicate on the "chain" field. It's identical to ChainEQ.
func Chain(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldChain, v))
}

// TokenSymbol applies equality check predicate on the "token_symbol" field. It's identical to TokenSymbolEQ.
func TokenSymbol(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldTokenSymbol, v))
}

// TokenContract applies equality check predicate on the "token_contract" field. It's identical to TokenContractEQ.
func TokenContract(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldTokenContract, v))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldTxHash, v))
}

// LogIndex applies equality check predicate on the "log_index" field. It's identical to LogIndexEQ.
func LogIndex(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldLogIndex, v))
}

// BlockNumber applies equality check predicate on the "block_number" field. It's identical to BlockNumberEQ.
func BlockNumber(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldBlockNumber, v))
}

// BlockHash applies equality check predicate on the "block_hash" field. It's identical to BlockHashEQ.
func BlockHash(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldBlockHash, v))
}

// FromAddress applies equality check predicate on the "from_address" field. It's identical to FromAddressEQ.
func FromAddress(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldFromAddress, v))
}

// ToAddress applies equality check predicate on the "to_address" field. It's identical to ToAddressEQ.
func ToAddress(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldToAddress, v))
}

// AmountRaw applies equality check predicate on the "amount_raw" field. It's identical to AmountRawEQ.
func AmountRaw(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldAmountRaw, v))
}

// AmountCredit applies equality check predicate on the "amount_credit" field. It's identical to AmountCreditEQ.
func AmountCredit(v float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldAmountCredit, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldStatus, v))
}

// CreditedAt applies equality check predicate on the "credited_at" field. It's identical to CreditedAtEQ.
func CreditedAt(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldCreditedAt, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldUserID, v))
}

// ChainEQ applies the EQ predicate on the "chain" field.
func ChainEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldChain, v))
}

// ChainNEQ applies the NEQ predicate on the "chain" field.
func ChainNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldChain, v))
}

// ChainIn applies the In predicate on the "chain" field.
func ChainIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldChain, vs...))
}

// ChainNotIn applies the NotIn predicate on the "chain" field.
func ChainNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldChain, vs...))
}

// ChainGT applies the GT predicate on the "chain" field.
func ChainGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldChain, v))
}

// ChainGTE applies the GTE predicate on the "chain" field.
func ChainGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldChain, v))
}

// ChainLT applies the LT predicate on the "chain" field.
func ChainLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldChain, v))
}

// ChainLTE applies the LTE predicate on the "chain" field.
func ChainLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldChain, v))
}

// ChainContains applies the Contains predicate on the "chain" field.
func ChainContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldChain, v))
}

// ChainHasPrefix applies the HasPrefix predicate on the "chain" field.
func ChainHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldChain, v))
}

// ChainHasSuffix applies the HasSuffix predicate on the "chain" field.
func ChainHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldChain, v))
}

// ChainEqualFold applies the EqualFold predicate on the "chain" field.
func ChainEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldChain, v))
}

// ChainContainsFold applies the ContainsFold predicate on the "chain" field.
func ChainContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldChain, v))
}

// TokenSymbolEQ applies the EQ predicate on the "token_symbol" field.
func TokenSymbolEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldTokenSymbol, v))
}

// TokenSymbolNEQ applies the NEQ predicate on the "token_symbol" field.
func TokenSymbolNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldTokenSymbol, v))
}

// TokenSymbolIn applies the In predicate on the "token_symbol" field.
func TokenSymbolIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldTokenSymbol, vs...))
}

// TokenSymbolNotIn applies the NotIn predicate on the "token_symbol" field.
func TokenSymbolNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldTokenSymbol, vs...))
}

// TokenSymbolGT applies the GT predicate on the "token_symbol" field.
func TokenSymbolGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldTokenSymbol, v))
}

// TokenSymbolGTE applies the GTE predicate on the "token_symbol" field.
func TokenSymbolGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldTokenSymbol, v))
}

// TokenSymbolLT applies the LT predicate on the "token_symbol" field.
func TokenSymbolLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldTokenSymbol, v))
}

// TokenSymbolLTE applies the LTE predicate on the "token_symbol" field.
func TokenSymbolLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldTokenSymbol, v))
}

// TokenSymbolContains applies the Contains predicate on the "token_symbol" field.
func TokenSymbolContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldTokenSymbol, v))
}

// TokenSymbolHasPrefix applies the HasPrefix predicate on the "token_symbol" field.
func TokenSymbolHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldTokenSymbol, v))
}

// TokenSymbolHasSuffix applies the HasSuffix predicate on the "token_symbol" field.
func TokenSymbolHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldTokenSymbol, v))
}

// TokenSymbolEqualFold applies the EqualFold predicate on the "token_symbol" field.
func TokenSymbolEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldTokenSymbol, v))
}

// TokenSymbolContainsFold applies the ContainsFold predicate on the "token_symbol" field.
func TokenSymbolContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldTokenSymbol, v))
}

// TokenContractEQ applies the EQ predicate on the "token_contract" field.
func TokenContractEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldTokenContract, v))
}

// TokenContractNEQ applies the NEQ predicate on the "token_contract" field.
func TokenContractNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldTokenContract, v))
}

// TokenContractIn applies the In predicate on the "token_contract" field.
func TokenContractIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldTokenContract, vs...))
}

// TokenContractNotIn applies the NotIn predicate on the "token_contract" field.
func TokenContractNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldTokenContract, vs...))
}

// TokenContractGT applies the GT predicate on the "token_contract" field.
func TokenContractGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldTokenContract, v))
}

// TokenContractGTE applies the GTE predicate on the "token_contract" field.
func TokenContractGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldTokenContract, v))
}

// TokenContractLT applies the LT predicate on the "token_contract" field.
func TokenContractLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldTokenContract, v))
}

// TokenContractLTE applies the LTE predicate on the "token_contract" field.
func TokenContractLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldTokenContract, v))
}

// TokenContractContains applies the Contains predicate on the "token_contract" field.
func TokenContractContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldTokenContract, v))
}

// TokenContractHasPrefix applies the HasPrefix predicate on the "token_contract" field.
func TokenContractHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldTokenContract, v))
}

// TokenContractHasSuffix applies the HasSuffix predicate on the "token_contract" field.
func TokenContractHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldTokenContract, v))
}

// TokenContractEqualFold applies the EqualFold predicate on the "token_contract" field.
func TokenContractEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldTokenContract, v))
}

// TokenContractContainsFold applies the ContainsFold predicate on the "token_contract" field.
func TokenContractContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldTokenContract, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldTxHash, v))
}

// LogIndexEQ applies the EQ predicate on the "log_index" field.
func LogIndexEQ(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldLogIndex, v))
}

// LogIndexNEQ applies the NEQ predicate on the "log_index" field.
func LogIndexNEQ(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldLogIndex, v))
}

// LogIndexIn applies the In predicate on the "log_index" field.
func LogIndexIn(vs ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldLogIndex, vs...))
}

// LogIndexNotIn applies the NotIn predicate on the "log_index" field.
func LogIndexNotIn(vs ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldLogIndex, vs...))
}

// LogIndexGT applies the GT predicate on the "log_index" field.
func LogIndexGT(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldLogIndex, v))
}

// LogIndexGTE applies the GTE predicate on the "log_index" field.
func LogIndexGTE(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldLogIndex, v))
}

// LogIndexLT applies the LT predicate on the "log_index" field.
func LogIndexLT(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldLogIndex, v))
}

// LogIndexLTE applies the LTE predicate on the "log_index" field.
func LogIndexLTE(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldLogIndex, v))
}

// BlockNumberEQ applies the EQ predicate on the "block_number" field.
func BlockNumberEQ(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldBlockNumber, v))
}

// BlockNumberNEQ applies the NEQ predicate on the "block_number" field.
func BlockNumberNEQ(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldBlockNumber, v))
}

// BlockNumberIn applies the In predicate on the "block_number" field.
func BlockNumberIn(vs ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldBlockNumber, vs...))
}

// BlockNumberNotIn applies the NotIn predicate on the "block_number" field.
func BlockNumberNotIn(vs ...int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldBlockNumber, vs...))
}

// BlockNumberGT applies the GT predicate on the "block_number" field.
func BlockNumberGT(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldBlockNumber, v))
}

// BlockNumberGTE applies the GTE predicate on the "block_number" field.
func BlockNumberGTE(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldBlockNumber, v))
}

// BlockNumberLT applies the LT predicate on the "block_number" field.
func BlockNumberLT(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldBlockNumber, v))
}

// BlockNumberLTE applies the LTE predicate on the "block_number" field.
func BlockNumberLTE(v int64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldBlockNumber, v))
}

// BlockHashEQ applies the EQ predicate on the "block_hash" field.
func BlockHashEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldBlockHash, v))
}

// BlockHashNEQ applies the NEQ predicate on the "block_hash" field.
func BlockHashNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldBlockHash, v))
}

// BlockHashIn applies the In predicate on the "block_hash" field.
func BlockHashIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldBlockHash, vs...))
}

// BlockHashNotIn applies the NotIn predicate on the "block_hash" field.
func BlockHashNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldBlockHash, vs...))
}

// BlockHashGT applies the GT predicate on the "block_hash" field.
func BlockHashGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldBlockHash, v))
}

// BlockHashGTE applies the GTE predicate on the "block_hash" field.
func BlockHashGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldBlockHash, v))
}

// BlockHashLT applies the LT predicate on the "block_hash" field.
func BlockHashLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldBlockHash, v))
}

// BlockHashLTE applies the LTE predicate on the "block_hash" field.
func BlockHashLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldBlockHash, v))
}

// BlockHashContains applies the Contains predicate on the "block_hash" field.
func BlockHashContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldBlockHash, v))
}

// BlockHashHasPrefix applies the HasPrefix predicate on the "block_hash" field.
func BlockHashHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldBlockHash, v))
}

// BlockHashHasSuffix applies the HasSuffix predicate on the "block_hash" field.
func BlockHashHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldBlockHash, v))
}

// BlockHashEqualFold applies the EqualFold predicate on the "block_hash" field.
func BlockHashEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldBlockHash, v))
}

// BlockHashContainsFold applies the ContainsFold predicate on the "block_hash" field.
func BlockHashContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldBlockHash, v))
}

// FromAddressEQ applies the EQ predicate on the "from_address" field.
func FromAddressEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldFromAddress, v))
}

// FromAddressNEQ applies the NEQ predicate on the "from_address" field.
func FromAddressNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldFromAddress, v))
}

// FromAddressIn applies the In predicate on the "from_address" field.
func FromAddressIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldFromAddress, vs...))
}

// FromAddressNotIn applies the NotIn predicate on the "from_address" field.
func FromAddressNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldFromAddress, vs...))
}

// FromAddressGT applies the GT predicate on the "from_address" field.
func FromAddressGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldFromAddress, v))
}

// FromAddressGTE applies the GTE predicate on the "from_address" field.
func FromAddressGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldFromAddress, v))
}

// FromAddressLT applies the LT predicate on the "from_address" field.
func FromAddressLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldFromAddress, v))
}

// FromAddressLTE applies the LTE predicate on the "from_address" field.
func FromAddressLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldFromAddress, v))
}

// FromAddressContains applies the Contains predicate on the "from_address" field.
func FromAddressContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldFromAddress, v))
}

// FromAddressHasPrefix applies the HasPrefix predicate on the "from_address" field.
func FromAddressHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldFromAddress, v))
}

// FromAddressHasSuffix applies the HasSuffix predicate on the "from_address" field.
func FromAddressHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldFromAddress, v))
}

// FromAddressEqualFold applies the EqualFold predicate on the "from_address" field.
func FromAddressEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldFromAddress, v))
}

// FromAddressContainsFold applies the ContainsFold predicate on the "from_address" field.
func FromAddressContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldFromAddress, v))
}

// ToAddressEQ applies the EQ predicate on the "to_address" field.
func ToAddressEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldToAddress, v))
}

// ToAddressNEQ applies the NEQ predicate on the "to_address" field.
func ToAddressNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldToAddress, v))
}

// ToAddressIn applies the In predicate on the "to_address" field.
func ToAddressIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldToAddress, vs...))
}

// ToAddressNotIn applies the NotIn predicate on the "to_address" field.
func ToAddressNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldToAddress, vs...))
}

// ToAddressGT applies the GT predicate on the "to_address" field.
func ToAddressGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldToAddress, v))
}

// ToAddressGTE applies the GTE predicate on the "to_address" field.
func ToAddressGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldToAddress, v))
}

// ToAddressLT applies the LT predicate on the "to_address" field.
func ToAddressLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldToAddress, v))
}

// ToAddressLTE applies the LTE predicate on the "to_address" field.
func ToAddressLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldToAddress, v))
}

// ToAddressContains applies the Contains predicate on the "to_address" field.
func ToAddressContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldToAddress, v))
}

// ToAddressHasPrefix applies the HasPrefix predicate on the "to_address" field.
func ToAddressHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldToAddress, v))
}

// ToAddressHasSuffix applies the HasSuffix predicate on the "to_address" field.
func ToAddressHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldToAddress, v))
}

// ToAddressEqualFold applies the EqualFold predicate on the "to_address" field.
func ToAddressEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldToAddress, v))
}

// ToAddressContainsFold applies the ContainsFold predicate on the "to_address" field.
func ToAddressContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldToAddress, v))
}

// AmountRawEQ applies the EQ predicate on the "amount_raw" field.
func AmountRawEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldAmountRaw, v))
}

// AmountRawNEQ applies the NEQ predicate on the "amount_raw" field.
func AmountRawNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldAmountRaw, v))
}

// AmountRawIn applies the In predicate on the "amount_raw" field.
func AmountRawIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldAmountRaw, vs...))
}

// AmountRawNotIn applies the NotIn predicate on the "amount_raw" field.
func AmountRawNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldAmountRaw, vs...))
}

// AmountRawGT applies the GT predicate on the "amount_raw" field.
func AmountRawGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldAmountRaw, v))
}

// AmountRawGTE applies the GTE predicate on the "amount_raw" field.
func AmountRawGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldAmountRaw, v))
}

// AmountRawLT applies the LT predicate on the "amount_raw" field.
func AmountRawLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldAmountRaw, v))
}

// AmountRawLTE applies the LTE predicate on the "amount_raw" field.
func AmountRawLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldAmountRaw, v))
}

// AmountRawContains applies the Contains predicate on the "amount_raw" field.
func AmountRawContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldAmountRaw, v))
}

// AmountRawHasPrefix applies the HasPrefix predicate on the "amount_raw" field.
func AmountRawHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldAmountRaw, v))
}

// AmountRawHasSuffix applies the HasSuffix predicate on the "amount_raw" field.
func AmountRawHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldAmountRaw, v))
}

// AmountRawEqualFold applies the EqualFold predicate on the "amount_raw" field.
func AmountRawEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldAmountRaw, v))
}

// AmountRawContainsFold applies the ContainsFold predicate on the "amount_raw" field.
func AmountRawContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldAmountRaw, v))
}

// AmountCreditEQ applies the EQ predicate on the "amount_credit" field.
func AmountCreditEQ(v float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldAmountCredit, v))
}

// AmountCreditNEQ applies the NEQ predicate on the "amount_credit" field.
func AmountCreditNEQ(v float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldAmountCredit, v))
}

// AmountCreditIn applies the In predicate on the "amount_credit" field.
func AmountCreditIn(vs ...float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldAmountCredit, vs...))
}

// AmountCreditNotIn applies the NotIn predicate on the "amount_credit" field.
func AmountCreditNotIn(vs ...float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldAmountCredit, vs...))
}

// AmountCreditGT applies the GT predicate on the "amount_credit" field.
func AmountCreditGT(v float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldAmountCredit, v))
}

// AmountCreditGTE applies the GTE predicate on the "amount_credit" field.
func AmountCreditGTE(v float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldAmountCredit, v))
}

// AmountCreditLT applies the LT predicate on the "amount_credit" field.
func AmountCreditLT(v float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldAmountCredit, v))
}

// AmountCreditLTE applies the LTE predicate on the "amount_credit" field.
func AmountCreditLTE(v float64) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldAmountCredit, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldStatus, v))
}

// CreditedAtEQ applies the EQ predicate on the "credited_at" field.
func CreditedAtEQ(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldCreditedAt, v))
}

// CreditedAtNEQ applies the NEQ predicate on the "credited_at" field.
func CreditedAtNEQ(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldCreditedAt, v))
}

// CreditedAtIn applies the In predicate on the "credited_at" field.
func CreditedAtIn(vs ...time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldCreditedAt, vs...))
}

// CreditedAtNotIn applies the NotIn predicate on the "credited_at" field.
func CreditedAtNotIn(vs ...time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldCreditedAt, vs...))
}

// CreditedAtGT applies the GT predicate on the "credited_at" field.
func CreditedAtGT(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldCreditedAt, v))
}

// CreditedAtGTE applies the GTE predicate on the "credited_at" field.
func CreditedAtGTE(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldCreditedAt, v))
}

// CreditedAtLT applies the LT predicate on the "credited_at" field.
func CreditedAtLT(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldCreditedAt, v))
}

// CreditedAtLTE applies the LTE predicate on the "credited_at" field.
func CreditedAtLTE(v time.Time) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldCreditedAt, v))
}

// CreditedAtIsNil applies the IsNil predicate on the "credited_at" field.
func CreditedAtIsNil() predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIsNull(FieldCreditedAt))
}

// CreditedAtNotNil applies the NotNil predicate on the "credited_at" field.
func CreditedAtNotNil() predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotNull(FieldCreditedAt))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.FieldContainsFold(FieldErrorMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OnchainDeposit) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OnchainDeposit) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OnchainDeposit) predicate.OnchainDeposit {
	return predicate.OnchainDeposit(sql.NotPredicates(p))
}
